# Run: docker compose up -d
name: sprint-to-doc
services:
  qdrant:
    container_name: sprint-to-doc-qdrant
    image: qdrant/qdrant:dev
    restart: no # always
    ports:
      - 6333:6333 # Qdrant API
      - 6334:6334 # Qdrant gRPC
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant/storage

  ollama:
    container_name: sprint-to-doc-ollama
    image: ollama/ollama:0.11.7
    restart: no # always
    ports:
      - 11434:11434
    expose:
      - 11434
    volumes:
      - ./ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

configs:
  qdrant_config:
    content: |
      log_level: INFO
